language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - pytest --cov --cov-report=html

after_success:
  - coveralls
